# https://github.com/xu-cheng/latex-action?tab=readme-ov-file#example

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "*.tex"
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrndorffGraduatePhysicsSolutions.zip
          path: "*.pdf"
      # Try to also upload as release
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.pdf"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Publishing latest solutions"
