# https://github.com/marketplace/actions/upload-files-to-a-github-release

name: Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "*.tex"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.pdf"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Publishing latest solutions"
